name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 6'

env:
  CI: "ON"
  HOMEBREW_NO_ANALYTICS: "ON"
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"
  BUILD_DIR: _build
  CMAKE_OPTIONS: >-
    -DCMAKE_BUILD_TYPE=Debug

jobs:
  gcc-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set Compiler (Linux)
      if: contains(matrix.os, 'ubuntu')
      run: |
        echo "FC=gfortran" >> $GITHUB_ENV
        echo "CC=gcc" >> $GITHUB_ENV

    - name: Set Compiler (OSX)
      if: contains(matrix.os, 'macos')
      run: |
        echo "FC=gfortran-9" >> $GITHUB_ENV
        echo "CC=gcc-9" >> $GITHUB_ENV

    - name: Install cmake
      run: pip3 install cmake ninja fypp

    - name: Configure build
      run: >-
        cmake -B ${BUILD_DIR} -G Ninja
        -DCMAKE_INSTALL_PREFIX=${PWD}/_install
        ${CMAKE_OPTIONS}

    - name: Build project
      run: cmake --build ${BUILD_DIR}

    - name: Run regression tests
      run: |
        pushd ${BUILD_DIR}
        ctest -j 2 --output-on-failure
        popd

    - name: Install project
      run: |
        cmake --install ${BUILD_DIR}

  # Test MinGW native compilation
  mingw-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          git
          mingw-w64-${{ matrix.arch }}-gcc-fortran
          mingw-w64-${{ matrix.arch }}-python
          mingw-w64-${{ matrix.arch }}-python-pip
          mingw-w64-${{ matrix.arch }}-cmake
          mingw-w64-${{ matrix.arch }}-ninja

    - name: Install fypp
      run: pip install fypp

    - name: Configure build
      run: >-
        cmake -B ${BUILD_DIR} -G Ninja
        -DCMAKE_INSTALL_PREFIX=${PWD}/_install
        ${CMAKE_OPTIONS}
      env:
        FC: gfortran
        CC: gcc

    - name: Build project
      run: cmake --build ${BUILD_DIR}

    - name: Run regression tests
      run: |
        pushd ${BUILD_DIR}
        ctest -j 2 --output-on-failure
        popd

    - name: Install project
      run: |
        cmake --install ${BUILD_DIR}
